{
    "images": [
      { "id": 1, "src": "/images/Art-1.jpeg", "alt": "Art1" },
      { "id": 2, "src": "/images/Art-2.jpeg", "alt": "Art2" },
      { "id": 3, "src": "/images/Art-3.jpeg", "alt": "Art3" },
      { "id": 4, "src": "/images/Art-4.jpeg", "alt": "Art4" },
      { "id": 5, "src": "/images/Art-5.jpeg", "alt": "Art5" },
      { "id": 6, "src": "/images/Art-6.jpeg", "alt": "Art6" },
      { "id": 7, "src": "/images/Art-7.jpeg", "alt": "Art7" },
      { "id": 8, "src": "/images/Art-8.jpeg", "alt": "Art8" },
      { "id": 9, "src": "/images/Art-9.jpeg", "alt": "Art9" },
      { "id": 10, "src": "/images/Art-10.jpeg", "alt": "Art10" },
      { "id": 11, "src": "/images/Art-11.jpeg", "alt": "Art11" },
      { "id": 12, "src": "/images/Art-12.jpg", "alt": "Art12" },
      { "id": 13, "src": "/images/Art-13.jpg", "alt": "Art13" },
      { "id": 14, "src": "/images/Art-14.jpg", "alt": "Art14" },
      { "id": 15, "src": "/images/Art-15.jpg", "alt": "Art15" },
      { "id": 16, "src": "/images/Art-16.jpg", "alt": "Art16" },
      { "id": 17, "src": "/images/Art-17.jpg", "alt": "Art17" },
      { "id": 18, "src": "/images/Art-18.jpg", "alt": "Art18" },
      { "id": 19, "src": "/images/Art-19.jpg", "alt": "Art19" },
      { "id": 20, "src": "/images/Art-20.jpg", "alt": "Art20" },
      { "id": 21, "src": "/images/Art-21.jpg", "alt": "Art21" },
      { "id": 22, "src": "/images/Art-22.jpg", "alt": "Art22" },
      { "id": 23, "src": "/images/Art-23.jpg", "alt": "Art23" },
      { "id": 24, "src": "/images/Art-24.jpg", "alt": "Art24" },
      { "id": 25, "src": "/images/Art-25.jpg", "alt": "Art25" },
      { "id": 26, "src": "/images/Art-26.jpg", "alt": "Art26" },
      { "id": 27, "src": "/images/Author.jpeg", "alt": "Author" },
      { "id": 28, "src": "/images/Background.jpeg", "alt": "Background" },
      { "id": 26, "src": "/images/Background-2.jpeg", "alt": "Background2" },
      { "id": 26, "src": "/images/Reel.mp4", "alt": "Reel" },
    ]
  }
  